### PR TITLE
Fix _.extend usage issue, which override defaults data

### PR DESCRIPTION
**Pull request by aivus**

### CODE REVIEW

**Comment by s0ph1e** [comment]
Thanks :thumbsup:
Can you also fix same issues in tests?

**Comment by aivus** [comment]
Yeap. Already fixed.

**Comment by s0ph1e** [comment]
I think it would be better to pass params directly to function, without `extends`. 
Something like 
```
scraper.scrape({
    url: 'http://example.com',
    directory: '/dir',
    .....
})
```

**Comment by s0ph1e** [comment]
@aivus what do you think?

**Comment by aivus** [comment]
I think we should leave `defaultOptions` like now. In the future, we can add to it required options.

**Pull request merged**
