### PR TITLE
Add headers to the originalResources collection before resolving

### PR DESCRIPTION
**Pull request by Flamenco**
We find it very useful to save the returned headers along with the web page.

### CODE REVIEW

**Comment by s0ph1e** [comment]
Hi 
Thanks for your contribution

Could you please provide an example of use-case for headers?

**Comment by Flamenco** [comment]
```
console.log(`${url} is loading...`);
    return scrape(opts)
        .then((result) => {
            console.log(`${url} was cached.`);
            const item = result.find(item => item.getUrl() === url);
            updateStatus(directory, CacheUpdateStatus.Created, item ? item.getHeaders() : undefined);
            return CacheUpdateStatus.Created;
        })
        .catch(error => {
            console.log(`${url} error: ${error.toString()}`);
            updateStatus(directory, CacheUpdateStatus.Error);
            return CacheUpdateStatus.Error;
        });
```

My update status function writes a json file next to the index.html file.  This json file includes the results of the get request.  I can use the header information to get fields such as last-updated, max-age, and no-store, and use said information to invalidate.

I am hoping to add some logic in another PR to detect if a site has not changed since the last scrape...

**Comment by s0ph1e** [comment]
@Flamenco 

1. I think using headers from one response to determine if site was changed is not correct. 
For example, you have html page with images. If image was changed, but its name remains the same - html will be the same and have same headers. In your case it means that nothing changed but in reality image is different.

2. I'm not sure that I understand why do you need to check headers **after** downloading.
Especially if you need headers only for original urls.
I think it would be better to send HEAD request **before** and then if headers changed - download new version of site. In this case you will download site only when it was changed.

Please correct me if I'm wrong
For now it seems like a solution for your special case and I'm not sure that it is needed in this module

**Comment by Flamenco** [comment]
@s0ph1e ,  I am sorry you can't see the benefits of getting the header information from the site you are scraping.  We track the content of the index.html page, so that's the only header we need.  The header information is already loaded for each resource, so it's not using any more memory, processing, or bandwidth.  The PR stores the header in each resource, not just the index page;  So if you wanted the headers from images, for example, you can get those too.  Whether it's our use-case or not, I think many user would benefit from the addition.  In fact, our internal fork changed the API for scrape to return {originalResources, loadedResources} instead of originalResources so we can get at any header that was spidered.

We considered adding a callback function after each resource was loaded, but it was cleaner to just store the header in the resource.

In response to item #2, we can go to each saved page, check the header, and compare that to the current site's info in order to notify the user and/or re-cache the page.  I don't see how else to get the last-modified header from the site you had loaded in the past without submitting another request after calling scrape().  Please correct me if I am missing something here.

Finally, we allow the user to searching the both the site content and header information while offline.

It makes sense to store metadata when you load a site, such as the current timestamp, the source url, and the response headers.  In Chrome, for example, when you save a webpage complete, it adds metadata information to the index.html page itself.

I hope this clears things up.

**Comment by Flamenco** [comment]
One more thing.  We have no way to get the content type of a downloaded file with no extension without having access to the response header.  Or verifying the content type of a resource that has an extension.

**Comment by s0ph1e** [comment]
#### As for caching/notifying
Yes, you are right, there is no way to get last-modified header of downloaded site without sending additional request.
I'm just curious why do you want to do it **after** scrape, but not **before**?
As I understand you need to download new version of site if it was changed.
And you do something like this:
screenshot-creately com-2017-02-24-23-00-39
In this case `scrape` is called each time, but `invalidate` only if site was modified. 
Please note that scrape itself makes a lot of requests, it may be slow and it is called *each* time.


My suggestion was to save somewhere date of last scraping (not from headers, from `Date.now()` for example), make HEAD req to url (it will not be slow because it returns just headers) and if site was modified - call `scrape`, `invalidate`, etc. In this case we do additional request but heavy and slow `scrape` is called only *when needed*.
screenshot-creately com-2017-02-24-23-01-20


#### As for files without extensions
There are solutions which use [Magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_numbers_in_files) to determine file type by its content. For example, [file-type](https://github.com/sindresorhus/file-type)


BTW, in page saved by Chrome I see only one added comment:
```html
<!-- saved from url=(0055)https://example.com -->
```
Did you mean this metadata or something else?

The main purpose of this module is **to download website from internet to FS**.  Yes, it is possible and easy to add headers, timestamps, original text, etc. but I don't see large benefits of this and amount of redundant returned data scares me

**Comment by Flamenco** [comment]
I will upload a description of our use case later that shows how we use the headers.

I dont see why losing the returned mime-type and relying on magic numbers and/or file extension  is preferred. 

We have changed our outlook on this issue to use callbacks. Having the headers in callback for modified date, mime type, and size before the file is downloaded, and then after load but not saved, is ideal. We could then alter files, and also modify image and script references to remove ads, trackers, etc. 

BTW, the extra size of header metadata is less then .5% of the total site cache, and It is already downloaded so no bandwidth issue either.

**Pull request closed without merging**
